spring:
  profiles:
    active: local

  application:
    name: tailfriend
    
  datasource:
    url: jdbc:mysql://db-33p2cg-kr.vpc-pub-cdb.ntruss.com/tailfriends?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 3000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "${baseUrl}/api/login/oauth2/code/kakao"
            scope:
              - account_email
            client-authentication-method: client_secret_post
            client-name: Kakao
          
          naver:
            authorization-grant-type: authorization_code
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "${baseUrl}/api/login/oauth2/code/naver"
            scope:
              - account_email
            client-authentication-method: client_secret_post
            client-name: Naver
          
          google:
            authorization-grant-type: authorization_code
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${baseUrl}/api/login/oauth2/code/google"
            scope:
              - email
            client-authentication-method: client_secret_post
            client-name: Google
        
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  
jwt:
  secret: ${JWT_SECRET}
  token-validity: 86400

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    tf.tailfriend.user.controller: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG

URL: ${baseUrl}

ncp:
  end-point: ${NCP_END_POINT}
  region-name: ${NCP_REGION_NAME}
  access-key: ${NCR_USERNAME}
  secret-key: ${NCR_PASSWORD}
  bucket-name: ${NCP_BUCKET_NAME}
